### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AliNemati13** [thereedlegend/Gamee-Cheat#2]
**Describe the bug**
Program is not working anymore, maybe something is changed in Gamee (Game: Space Orbit).

**Screenshots**
![2](https://github.com/user-attachments/assets/23f52687-a7ab-46d2-8ef2-68ef25aa0506)

**Desktop:**
 - OS: [Windows 10]
 - Python [3.12.6]

**Comment by Kitsutemi** [comment]
It's a broken, maybe I can fix it later
